In [1]:
#Array Creation:
#Create a 1-dimensional array of integers from 1 to 10.
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# Create a 2-dimensional array with random float values of shape (3, 4).
Q2 = np.random.rand(3,4)
Q2

array([[0.13131795, 0.65673668, 0.18417414, 0.04176666],
       [0.71767251, 0.2561906 , 0.26747496, 0.07012209],
       [0.24153592, 0.44985466, 0.59757978, 0.34335065]])

In [3]:
# Create a 3-dimensional array of zeros with shape (2, 3, 4).
Q3 = np.zeros((2,3,4))
Q3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
#Array operations:
#Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.
Arr1 = np.array([1, 2, 3, 4, 5])
Arr2 = np.array([6, 7, 8, 9, 10])
Add = Arr1+Arr2
Add
Sub = Arr1-Arr2
Sub
Mul = Arr1*Arr2
Mul
div = Arr1/Arr2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [5]:
# Calculate the mean, median, and standard deviation of a given 1- dimensional array.
Arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(Arr)
mean
median = np.median(Arr)
median
std = np.std(Arr)
std



2.8722813232690143

In [6]:
# Reshape a 1-dimensional array into a 2-dimensional array of shape (3, 4).
Arr = np.arange(12)
twod_Arr = Arr.reshape((3,4))
twod_Arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# Reverse the order of elements in a 1-dimensional array.
Arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
rev = Arr[::-1]
rev


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [9]:
# Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
greater = arr[arr > 5]
greater

array([ 6,  7,  8,  9, 10, 11, 12])

In [10]:
#Array Broadcasting:
# Add a scalar value to each element of a 2-dimensional array.
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
scalar = arr + 5
scalar

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [11]:
# Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.
array1 = np.array([1, 2, 3, 4])
array2 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
mul = array1 * array2
mul

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

In [ ]:
#Linear Algebra:
